-- ============================================================================
-- PL/SQL: Data Manipulation Language (DML)
-- Description: Scripts for inserting, updating, and deleting data.
-- ============================================================================
