-- ============================================================================
-- PL/SQL: User-Defined Functions
-- Description: Scripts for defining and executing PL/SQL functions.
-- ============================================================================
