-- ============================================================================
-- PL/SQL: Queries & Reports
-- Description: SQL queries, joins, aggregations, and analytical statements.
-- ============================================================================
