-- ============================================================================
-- PL/SQL: Database Triggers
-- Description: Scripts for defining row-level and statement-level triggers.
-- ============================================================================
